/** OpenAPI request body schemas for external API write operations. */
export const OPENAPI_REQUEST_SCHEMAS: Record<string, Record<string, unknown>> = {
  CreateCategoryRequest: {
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string' },
      monthly_amount: { type: 'number' },
      current_balance: { type: 'number' },
      sort_order: { type: 'integer' },
      notes: { type: 'string', nullable: true },
      is_archived: { type: 'boolean' },
      category_type: { type: 'string', enum: ['monthly_expense', 'accumulation', 'target_balance'] },
      priority: { type: 'integer' },
      monthly_target: { type: 'number' },
      annual_target: { type: 'number' },
      target_balance: { type: 'number' },
    },
  },
  UpdateCategoryRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      monthly_amount: { type: 'number' },
      current_balance: { type: 'number' },
      sort_order: { type: 'integer' },
      notes: { type: 'string', nullable: true },
      is_archived: { type: 'boolean' },
      category_type: { type: 'string', enum: ['monthly_expense', 'accumulation', 'target_balance'] },
      priority: { type: 'integer' },
      monthly_target: { type: 'number' },
      annual_target: { type: 'number' },
      target_balance: { type: 'number' },
    },
  },
  ReorderCategoriesRequest: {
    type: 'object',
    required: ['categoryOrders'],
    properties: {
      categoryOrders: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'sort_order'],
          properties: { id: { type: 'integer' }, sort_order: { type: 'integer' } },
        },
      },
    },
  },
  BulkArchiveCategoriesRequest: {
    type: 'object',
    required: ['categoryIds'],
    properties: {
      categoryIds: { type: 'array', items: { type: 'integer' } },
      is_archived: { type: 'boolean', default: true },
    },
  },
  ManualAllocationRequest: {
    type: 'object',
    required: ['categoryId', 'amount'],
    properties: {
      categoryId: { type: 'integer' },
      amount: { type: 'number', minimum: 0, exclusiveMinimum: true },
      month: { type: 'string', description: 'YYYY-MM-01 format' },
    },
  },
  CreateAccountRequest: {
    type: 'object',
    required: ['name', 'balance', 'account_type'],
    properties: {
      name: { type: 'string' },
      balance: { type: 'number' },
      account_type: { type: 'string', enum: ['checking', 'savings', 'cash'] },
      include_in_totals: { type: 'boolean' },
      sort_order: { type: 'integer' },
    },
  },
  UpdateAccountRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      balance: { type: 'number' },
      account_type: { type: 'string', enum: ['checking', 'savings', 'cash'] },
      include_in_totals: { type: 'boolean' },
      sort_order: { type: 'integer' },
    },
  },
  CreateCreditCardRequest: {
    type: 'object',
    required: ['name', 'credit_limit', 'available_credit'],
    properties: {
      name: { type: 'string' },
      credit_limit: { type: 'number' },
      available_credit: { type: 'number' },
      statement_balance: { type: 'number', nullable: true },
      statement_balance_as_of: { type: 'string', format: 'date', nullable: true },
      include_in_totals: { type: 'boolean' },
      sort_order: { type: 'integer' },
    },
  },
  UpdateCreditCardRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      credit_limit: { type: 'number' },
      available_credit: { type: 'number' },
      statement_balance: { type: 'number', nullable: true },
      statement_balance_as_of: { type: 'string', format: 'date', nullable: true },
      include_in_totals: { type: 'boolean' },
      sort_order: { type: 'integer' },
    },
  },
  UpdateTransactionRequest: {
    type: 'object',
    properties: {
      description: { type: 'string' },
      amount: { type: 'number' },
      date: { type: 'string', format: 'date' },
      account_id: { type: 'integer', nullable: true },
      credit_card_id: { type: 'integer', nullable: true },
      category_id: { type: 'integer', nullable: true },
      merchant: { type: 'string', nullable: true },
      transaction_type: { type: 'string', enum: ['income', 'expense'] },
      notes: { type: 'string', nullable: true },
    },
  },
  CreateGoalRequest: {
    type: 'object',
    required: ['name', 'goal_type', 'monthly_contribution'],
    properties: {
      name: { type: 'string' },
      target_amount: { type: 'number' },
      target_date: { type: 'string', format: 'date', nullable: true },
      goal_type: { type: 'string', enum: ['envelope', 'account-linked', 'debt-paydown'] },
      monthly_contribution: { type: 'number' },
      linked_account_id: { type: 'integer', nullable: true },
      linked_category_id: { type: 'integer', nullable: true },
      linked_credit_card_id: { type: 'integer', nullable: true },
      linked_loan_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
    },
  },
  UpdateGoalRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      target_amount: { type: 'number' },
      target_date: { type: 'string', format: 'date', nullable: true },
      monthly_contribution: { type: 'number' },
      status: { type: 'string', enum: ['active', 'completed', 'overdue', 'paused'] },
      notes: { type: 'string', nullable: true },
      sort_order: { type: 'integer' },
    },
  },
  CreateLoanRequest: {
    type: 'object',
    required: ['name', 'balance'],
    properties: {
      name: { type: 'string' },
      balance: { type: 'number' },
      interest_rate: { type: 'number', nullable: true },
      minimum_payment: { type: 'number', nullable: true },
      institution: { type: 'string', nullable: true },
      include_in_net_worth: { type: 'boolean' },
    },
  },
  UpdateLoanRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      balance: { type: 'number' },
      interest_rate: { type: 'number', nullable: true },
      minimum_payment: { type: 'number', nullable: true },
      institution: { type: 'string', nullable: true },
      include_in_net_worth: { type: 'boolean' },
    },
  },
  CreateNonCashAssetRequest: {
    type: 'object',
    required: ['name', 'asset_type'],
    properties: {
      name: { type: 'string' },
      asset_type: { type: 'string' },
      current_value: { type: 'number' },
      estimated_return_percentage: { type: 'number' },
      is_rmd_qualified: { type: 'boolean' },
      is_liquid: { type: 'boolean' },
    },
  },
  UpdateNonCashAssetRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      asset_type: { type: 'string' },
      current_value: { type: 'number' },
      estimated_return_percentage: { type: 'number' },
      is_rmd_qualified: { type: 'boolean' },
      is_liquid: { type: 'boolean' },
    },
  },
  CreatePendingCheckRequest: {
    type: 'object',
    required: ['description', 'amount'],
    properties: {
      description: { type: 'string' },
      amount: { type: 'number' },
      type: { type: 'string', enum: ['expense', 'income'] },
    },
  },
  UpdatePendingCheckRequest: {
    type: 'object',
    properties: {
      description: { type: 'string' },
      amount: { type: 'number' },
      type: { type: 'string', enum: ['expense', 'income'] },
    },
  },
  CreateRecurringTransactionRequest: { type: 'object', additionalProperties: true },
  UpdateRecurringTransactionRequest: { type: 'object', additionalProperties: true },
  DetectRecurringTransactionsRequest: {
    type: 'object',
    properties: { lookbackMonths: { type: 'integer', default: 24 } },
  },
  CreateIncomeStreamRequest: {
    type: 'object',
    required: ['name', 'annual_income'],
    properties: {
      name: { type: 'string' },
      annual_income: { type: 'number' },
      tax_rate: { type: 'number' },
      pay_frequency: { type: 'string' },
      include_in_budget: { type: 'boolean' },
    },
  },
  UpdateIncomeStreamRequest: { type: 'object', additionalProperties: true },
  CreateIncomeSettingsRequest: { type: 'object', additionalProperties: true },
  CreatePreTaxDeductionRequest: { type: 'object', additionalProperties: true },
  IncomeBufferAmountRequest: {
    type: 'object',
    required: ['amount'],
    properties: { amount: { type: 'number', minimum: 0, exclusiveMinimum: true } },
  },
  CreateTagRequest: {
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string' },
      color: { type: 'string', nullable: true },
      description: { type: 'string', nullable: true },
    },
  },
  UpdateTagRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      color: { type: 'string', nullable: true },
      description: { type: 'string', nullable: true },
    },
  },
  CreateTagRuleRequest: {
    type: 'object',
    required: ['tag_id', 'rule_type', 'rule_value'],
    properties: {
      tag_id: { type: 'integer' },
      rule_type: { type: 'string', enum: ['category', 'merchant', 'description', 'amount'] },
      rule_value: { type: 'string' },
      priority: { type: 'integer' },
      is_active: { type: 'boolean' },
    },
  },
  BulkAssignTagsRequest: {
    type: 'object',
    required: ['transaction_ids', 'tag_ids'],
    properties: {
      transaction_ids: { type: 'array', items: { type: 'integer' } },
      tag_ids: { type: 'array', items: { type: 'integer' } },
    },
  },
  CreateMerchantGroupRequest: {
    type: 'object',
    required: ['display_name'],
    properties: { display_name: { type: 'string' } },
  },
  UpdateMerchantGroupRequest: {
    type: 'object',
    properties: { display_name: { type: 'string' } },
  },
  CreateMerchantMappingRequest: { type: 'object', additionalProperties: true },
  CreateMerchantCategoryRuleRequest: { type: 'object', additionalProperties: true },
  UpdateMerchantCategoryRuleRequest: { type: 'object', additionalProperties: true },
  CreateCsvImportTemplateRequest: { type: 'object', additionalProperties: true },
  CreateAutomaticImportSetupRequest: { type: 'object', additionalProperties: true },
  UpdateAutomaticImportSetupRequest: { type: 'object', additionalProperties: true },
  UpdateQueuedImportRequest: { type: 'object', additionalProperties: true },
  ApproveBatchImportsRequest: {
    type: 'object',
    required: ['ids'],
    properties: { ids: { type: 'array', items: { type: 'integer' } } },
  },
  UpdateSettingsRequest: {
    type: 'object',
    additionalProperties: { type: 'string' },
    description: 'Key-value settings to upsert',
  },
  UpdateNotificationRequest: {
    type: 'object',
    properties: { is_read: { type: 'boolean' } },
  },
  UpdateNotificationPreferencesRequest: {
    type: 'object',
    additionalProperties: {
      type: 'object',
      properties: {
        emailEnabled: { type: 'boolean' },
        inAppEnabled: { type: 'boolean' },
        settings: { type: 'object' },
      },
    },
  },
  UpdateRetirementForecastSettingsRequest: {
    type: 'object',
    additionalProperties: true,
  },
};
